# ExternalSecret khai báo cách sync secret từ AWS Secrets Manager vào Kubernetes Secret.
# ESO controller đọc remoteRef.key rồi tạo/refresh target Secret app-config trong namespace dev.
apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-app-config
  namespace: dev
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: app-config
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: w10/day2/demo-app
        property: username
    - secretKey: password
      remoteRef:
        key: w10/day2/demo-app
        property: password
    - secretKey: api_key
      remoteRef:
        key: w10/day2/demo-app
        property: api_key
