output "instance_public_ip" {
  description = "Public IP of the EC2 lab host."
  value       = aws_instance.lab.public_ip
}

output "ssh_private_key_path" {
  description = "Local SSH private key generated by the tls/local providers."
  value       = local_sensitive_file.private_key.filename
  sensitive   = true
}

output "ssh_command" {
  description = "SSH command for the lab host."
  value       = "ssh -i ${local_sensitive_file.private_key.filename} ec2-user@${aws_instance.lab.public_ip}"
  sensitive   = true
}

output "bootstrap_log_command" {
  description = "Use this after SSH to watch cloud-init bootstrap status."
  value       = "sudo tail -f /var/log/cloud-init-output.log"
}
